[env:teensy41]
platform = teensy@6.0.0
board = teensy41
framework = arduino
monitor_speed = 115200
lib_extra_dirs = ../shared
build_flags = -DUSB_SERIAL
lib_deps =
    https://github.com/tonton81/WDT_T4#1910b57d24468cd3419959118a2e1e6192f5e7fa
