#!/usr/bin/env python3
"""Generates flash-resident C++ track metadata table from config/tracks.csv."""
import csv
from pathlib import Path


def generate(csv_path: Path, output_path: Path) -> None:
    csv_path = Path(csv_path)
    output_path = Path(output_path)

    if not csv_path.exists():
        raise FileNotFoundError(f"CSV file not found: {csv_path}")

    tracks = []
    seen_tracks = set()

    with open(csv_path, mode="r", encoding="utf-8") as f:
        reader = csv.DictReader(f)
        required_cols = {"track", "duration_ms", "completion_guard_ms"}
        if not required_cols.issubset(set(reader.fieldnames or [])):
            raise ValueError(f"CSV missing required columns: {required_cols - set(reader.fieldnames or [])}")

        for row_num, row in enumerate(reader, start=2):
            try:
                track = int(row["track"].strip())
                duration_ms = int(row["duration_ms"].strip())
                guard_ms = int(row["completion_guard_ms"].strip())
            except (ValueError, KeyError) as e:
                raise ValueError(f"Line {row_num}: invalid integer value in CSV: {row}") from e

            if track < 1 or track > 255:
                raise ValueError(f"Line {row_num}: track {track} out of range (1..255)")
            if track in seen_tracks:
                raise ValueError(f"Line {row_num}: duplicate track {track}")
            if duration_ms < 0:
                raise ValueError(f"Line {row_num}: duration {duration_ms} cannot be negative")
            if guard_ms <= 0:
                raise ValueError(f"Line {row_num}: completion guard {guard_ms} must be positive")

            seen_tracks.add(track)
            tracks.append((track, duration_ms, guard_ms))

    # Sort deterministically by track number
    tracks.sort(key=lambda t: t[0])

    lines = [
        "// Auto-generated by tools/generate_track_catalog.py. Do not edit manually.",
        "#pragma once",
        "",
        "#include <cstdint>",
        "#include <cstddef>",
        "",
        "struct TrackInfo {",
        "    uint16_t track;",
        "    uint32_t duration_ms;",
        "    uint32_t completion_guard_ms;",
        "};",
        "",
        "const TrackInfo kTrackCatalog[] = {",
    ]

    for track, duration, guard in tracks:
        lines.append(f"    {{ {track}, {duration}u, {guard}u }},")

    lines.extend([
        "};",
        "const size_t kTrackCatalogCount = sizeof(kTrackCatalog) / sizeof(kTrackCatalog[0]);",
        "",
        "inline TrackInfo lookupTrack(uint8_t folder, uint16_t track) {",
        "    (void)folder;",
        "    for (size_t i = 0; i < kTrackCatalogCount; ++i) {",
        "        if (kTrackCatalog[i].track == track) {",
        "            return kTrackCatalog[i];",
        "        }",
        "    }",
        "    return TrackInfo{ track, 0u, 600000u };",
        "}",
        "",
    ])

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text("\n".join(lines), encoding="utf-8")


# PlatformIO pre-build hook (only active when run under SCons)
try:
    Import("env")  # type: ignore # noqa: F821
    root = Path(env.get("PROJECT_DIR", ".")).parent  # type: ignore # noqa: F821
    generate(root / "config/tracks.csv", root / "TEENSY_BODY_CONTROLLER/include/TrackCatalog.h")
except NameError:
    pass

if __name__ == "__main__":
    import sys
    if len(sys.argv) == 3:
        generate(Path(sys.argv[1]), Path(sys.argv[2]))
    else:
        root_dir = Path(__file__).resolve().parents[1]
        generate(root_dir / "config/tracks.csv", root_dir / "TEENSY_BODY_CONTROLLER/include/TrackCatalog.h")
